### ISSUE TITLE
UI update: open and close eye icon instead of checkboxes

### ISSUE THREAD

**Issue by loveshdongre** [loveshdongre/leetcode-enhancer#10]
The current implementation uses check boxes however, open and close eye icon conveys the function slightly better

**Comment by saptarshithe42** [comment]
This pull request is regarding issue https://github.com/loveshdongre/leetcode-enhancer/issues/10
Please review it

**Comment by natzelo** [comment]
I think we can close this issue now @loveshdongre ?
