### ISSUE TITLE
Columns from tables on "discuss" posts are deleted

### ISSUE THREAD

**Issue by 1cYx-pw8gM** [loveshdongre/leetcode-enhancer#14]
Thanks for your work on this amazing extension.
There is a bug when there are tables on a discussion post.

Below is an example post:

![image](https://user-images.githubusercontent.com/106346857/170558577-09d63d7a-985b-4111-855d-90c8419b97b3.png)

---

**When the "Status" option is unchecked from the extension options, the first column on all tables of the page is removed:**

![image](https://user-images.githubusercontent.com/106346857/170558523-27931073-9b4a-4004-9150-e5d821c17804.png)

**Comment by loveshdongre** [comment]
hi @1cYx-pw8gM 
Thank you for bringing this issue in light.
I have fixed this issue with the following commit id 49280fdddd51aea3be0d686bf321887358e9fcef

Do let me know if this issue still persists. I am closing this issue as of now.
Thanks!
