### ISSUE TITLE
Manifest upgrade from V2 to V3

### ISSUE THREAD

**Issue by loveshdongre** [loveshdongre/leetcode-enhancer#15]

**Comment by saptarshithe42** [comment]
https://stackoverflow.com/questions/63308160/how-to-migrate-manifest-version-2-to-v3-for-chrome-extension

you can follow this answer

**Comment by natzelo** [comment]
I would like to take this issue. Can you assign it to me @loveshdongre ?

**Comment by loveshdongre** [comment]
@natzelo 
Sure, thanks!

**Comment by natzelo** [comment]
@loveshdongre, made a pull request regarding this. Let me know if there are other issues I can help with :)
