### ISSUE TITLE
Implement Acceptance rate hiding in coding area

### ISSUE THREAD

**Issue by natzelo** [loveshdongre/leetcode-enhancer#26]
We already have a feature of hiding difficulty level in coding area, but we don't have one for hiding acceptance rate. Instead, the app removes the labels and keeps the values shown 

<img width="1360" alt="Screenshot 2023-07-01 at 7 01 14 PM" src="https://github.com/loveshdongre/leetcode-enhancer/assets/52002984/3f586d50-c0ae-4098-981d-286561e93a47">

**Comment by natzelo** [comment]
I would like to work on this feature @loveshdongre. Can you assign it to me please ?

**Comment by loveshdongre** [comment]
Hi @natzelo 
That's good suggestion, I've assigned the issue to you.
Thanks for picking it up!

**Comment by natzelo** [comment]
@loveshdongre I have opened a pull request #28 for this issue. Checkout the GIF to view the changes made to the UI and functionality before merging
Thanks!

**Comment by loveshdongre** [comment]
hi @natzelo 
Your code is merged. Will deploy in all the extension stores probably with a few more changes.
Will be creating an issue for mode 3 (old coding area) and an issue to update the UI.
Thanks!
