### ISSUE TITLE
Changing the default search engine setting in Chrome.

### ISSUE THREAD

**Issue by aadil42** [loveshdongre/leetcode-enhancer#35]
It changed the default search engine from Google to Bing in Chrome. And, it's not letting me switch back. I have to disable the extension to enable Google again.

**Comment by loveshdongre** [comment]
Have you tried disabling the search override by following going in settings > search engine
<img width="1512" alt="image" src="https://github.com/loveshdongre/leetcode-enhancer/assets/35028195/fd8605d5-9292-48c6-bd1b-c72761af939f">

**Comment by aadil42** [comment]
It started working by itself. But I did go to the Search Engine setting in the Chrome setting. I didn't find anything related to LeetCode-Enhancer. I mean, I didn't see the option that is in the screenshot. But It works now, I don't know how, but it does.

**Comment by loveshdongre** [comment]
Yeah released a new version so it's fixed.
