### ISSUE TITLE
Difficulty is not hidden.

### ISSUE THREAD

**Issue by aadil42** [loveshdongre/leetcode-enhancer#37]
Leetcode has introduced a new UI. Can't hide the difficulty level.

**Comment by amokam** [comment]
Yes, difficulty is not hidden in the coding area. I think most changes have been done on the coding area itself.

**Comment by aadil42** [comment]
Yeah, the new UI is so bad!! I mean, not because the extension is not working. In general, It is horrible.  The solved tag is F**ed up, When you submit it doesn't take you to your submission tab directly. It is just horrible.

**Comment by loveshdongre** [comment]
hi @aadil42 / @amokam 
Thanks for raising this issue. As mentioned by both of you the new UI is breaking the extension.
Challenge I'm facing is finding the selector in the code. On inspecting the code I found all the classes used are used in a really generic sense, thus modifying them can really easily create issue. Also, ids used are random and keep on changing on refresh thus making it difficult for finding the result.

Might require community to come up with a fix.

**Comment by aadil42** [comment]
They really f***ed us this time. Will see if there's a solution.

**Comment by loveshdongre** [comment]
hi @aadil42 / @amokam 
I've deployed a fix this time in version 1.58, one possible issue could be some lag.
Probably in the upcoming version will try to fix it.

Closing this thread as of now. Thanks for reaching out!
