### ISSUE TITLE
Not Working Properly 

### ISSUE THREAD

**Issue by eeshwar369** [loveshdongre/leetcode-enhancer#41]
Sometimes its working and sometimes its not working Properly
<img width="942" alt="image" src="https://github.com/user-attachments/assets/73e6d456-ab9b-4e25-8d71-81b6911d4766">
.

**Comment by loveshdongre** [comment]
Hi Eeshwar, 
Please answer the following questions and help in my in identifying the issue.
1. Is there any specific feature that is not working or the entire extension failed?
2. Are you using the latest version of the extension?
3. Which browser are you using? Have you tried changing it (As the extension is also available for firefox and edge)
4. On which url of leetcode issue is encountered?
5. Are you using the old/new UI of leetcode?

**Comment by eeshwar369** [comment]
1.Sometimes some of the features like acceptance, difficulty are visible to the user even it is hidden in the extension.
2.Yes i am using latest  version.
3.Chrome
4.There is no particular url i was using this just to hide the difficulty of problems but sometimes it is not working properly.
5.New UI

Bonus:-Its seems working fine now .I think you made some changes in it

**Comment by eeshwar369** [comment]
1.Sometimes some of the features like acceptance, difficulty are visible to the user even it is hidden in the extension.
2.Yes i am using latest  version.
3.Chrome
4.There is no particular url i was using this just to hide the difficulty of problems but sometimes it is not working properly.
5.New UI

Bonus:-Its seems working fine now .I think you made some changes in it

**Comment by loveshdongre** [comment]
I think it was because I turned on the debugger which made the extension slow in v1.66. Have fixed it in 1.67. Thanks for letting me know that the issue is resolved now!
